test:
  script:
  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && dpkg -i erlang-solutions_1.0_all.deb
  - apt-get update -qy
  - apt-get install -y elixir
  - mix local.hex --force
  - mix deps.get
  - mix test